[package]
name = "graphql"
version = "0.1.0"
authors = ["Wilson Giese <giese.wilson@gmail.com>"]
build = "build.rs"


[build-dependencies]
lalrpop = "0.12.5"

[dependencies]
lalrpop-util = "0.12.5"
regex = "0.2"
