//! Parser generation for the GraphQL language
//!
//! Spec:
//!     http://facebook.github.io/graphql/

use std::str::FromStr;

//! http://facebook.github.io/graphql/#sec-Int-Value
pub IntValue = {
    <IntegerPart>
};

pub IntegerPart = {
    <OptionalNegativeSign> "0",
    <OptionalNegativeSign> <NonZeroDigit> <Digit>
};


//! Symbols
Digit: str = r"[0-9]" => <>
NonZeroDigit: str = r"[1-9]" => <>
OptionalNegativeSign: str = r"-?" => <>
